package directiontranslator;

import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Takashi
 */
public class NewJDialog extends javax.swing.JDialog {

    private String translationLang = "en";
    private Languages languageCodeGenerator = new Languages();
    /**
     * Creates new form NewJDialog
     */
    public NewJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        initComponents();
//        System.out.println(languageCodeGenerator.getAllLangCodes());
//        moreLangComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(languageCodeGenerator.getAllLangCodes()));


     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        inputTextArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        outputTextArea = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        englishLangButton = new javax.swing.JButton();
        spanishLangButton = new javax.swing.JButton();
        moreLangComboBox = new javax.swing.JComboBox<>();
        hindiLangButton = new javax.swing.JButton();
        selectedLangLabel = new javax.swing.JLabel();
        northOrigLabel = new javax.swing.JLabel();
        westOrigLabel = new javax.swing.JLabel();
        southOrigLabel = new javax.swing.JLabel();
        eastOrigLabel = new javax.swing.JLabel();
        rightOrigLabel = new javax.swing.JLabel();
        leftOrigLabel = new javax.swing.JLabel();
        straightOrigLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        northTranLabel = new javax.swing.JLabel();
        westTranLabel = new javax.swing.JLabel();
        eastTranLabel = new javax.swing.JLabel();
        southTranLabel = new javax.swing.JLabel();
        leftTranLabel = new javax.swing.JLabel();
        straightTranLabel = new javax.swing.JLabel();
        rightTranLabel = new javax.swing.JLabel();
        detectedLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        inputTextArea.setColumns(20);
        inputTextArea.setLineWrap(true);
        inputTextArea.setRows(5);
        jScrollPane1.setViewportView(inputTextArea);

        outputTextArea.setColumns(20);
        outputTextArea.setLineWrap(true);
        outputTextArea.setRows(5);
        jScrollPane2.setViewportView(outputTextArea);

        jButton1.setBackground(new java.awt.Color(0, 238, 238));
        jButton1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jButton1.setText("Translate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        englishLangButton.setText("English");
        englishLangButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                englishLangButtonActionPerformed(evt);
            }
        });

        spanishLangButton.setText("Spanish");
        spanishLangButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spanishLangButtonActionPerformed(evt);
            }
        });

        moreLangComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Afrikaans", "Arabic", "Bosnian (Latin)", "Bulgarian", "Catalan", "Chinese Simplified", "Chinese Traditional", "Croatian", "Czech", "Danish", "Dutch", "English", "Estonian", "Finnish", "French", "German", "Greek", "Haitian Creole", "Hebrew", "Hindi", "Hmong Daw", "Hungarian", "Indonesian", "Italian", "Japanese", "Kiswahili", "Klingon", "Klingon (pIqaD)", "Korean", "Latvian", "Lithuanian", "Malay", "Maltese", "Norwegian", "Persian", "Polish", "Portuguese", "Querétaro Otomi", "Romanian", "Russian", "Serbian (Cyrillic)", "Serbian (Latin)", "Slovak", "Slovenian", "Spanish", "Swedish", "Thai", "Turkish", "Ukrainian", "Urdu", "Vietnamese", "Welsh", "Yucatec Maya" }));
        moreLangComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moreLangComboBoxActionPerformed(evt);
            }
        });

        hindiLangButton.setText("Hindi");
        hindiLangButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hindiLangButtonActionPerformed(evt);
            }
        });

        selectedLangLabel.setText("Translated to ");

        northOrigLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        northOrigLabel.setText("North");

        westOrigLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        westOrigLabel.setText("West");

        southOrigLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        southOrigLabel.setText("South");

        eastOrigLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        eastOrigLabel.setText("East");

        rightOrigLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        rightOrigLabel.setText("Right");

        leftOrigLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        leftOrigLabel.setText("Left");

        straightOrigLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        straightOrigLabel.setText("Straight");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setToolTipText("");

        jPanel1.setBackground(new java.awt.Color(218, 238, 238));

        northTranLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        northTranLabel.setText("North");

        westTranLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        westTranLabel.setText("West");

        eastTranLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        eastTranLabel.setText("East");

        southTranLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        southTranLabel.setText("South");

        leftTranLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        leftTranLabel.setText("Left");

        straightTranLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        straightTranLabel.setText("Straight");

        rightTranLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        rightTranLabel.setText("Right");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(westTranLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(eastTranLabel)
                .addGap(64, 64, 64))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(leftTranLabel)
                .addGap(79, 79, 79)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(southTranLabel)
                            .addComponent(northTranLabel))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(straightTranLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addComponent(rightTranLabel)
                        .addGap(30, 30, 30))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(northTranLabel)
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(westTranLabel)
                    .addComponent(eastTranLabel))
                .addGap(30, 30, 30)
                .addComponent(southTranLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(leftTranLabel)
                    .addComponent(straightTranLabel)
                    .addComponent(rightTranLabel))
                .addContainerGap())
        );

        detectedLabel.setText("Detected Language: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(southOrigLabel)
                            .addComponent(northOrigLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(westOrigLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(eastOrigLabel))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(leftOrigLabel)
                                .addGap(37, 37, 37)
                                .addComponent(straightOrigLabel)
                                .addGap(33, 33, 33)
                                .addComponent(rightOrigLabel))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(detectedLabel)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(37, 37, 37)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectedLangLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane2)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(englishLangButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(spanishLangButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(hindiLangButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(moreLangComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(selectedLangLabel)
                            .addComponent(detectedLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(englishLangButton)
                                    .addComponent(spanishLangButton)
                                    .addComponent(hindiLangButton)
                                    .addComponent(moreLangComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(northOrigLabel)
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(eastOrigLabel)
                                    .addComponent(westOrigLabel))
                                .addGap(24, 24, 24)
                                .addComponent(southOrigLabel)
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(leftOrigLabel)
                                    .addComponent(rightOrigLabel)
                                    .addComponent(straightOrigLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(84, 84, 84))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Translator tran;
        try {
            tran = new Translator();
            String inputText = inputTextArea.getText();
//            System.out.println(translationLang);
            String outputText = tran.translate(inputText, translationLang);
            outputTextArea.setText(parseTranslatorXML(outputText));
//            System.out.println(tran.detect(inputText));
//            detectedLabel.setText(tran.detect(inputText));
        } catch (IOException ex) {
            Logger.getLogger(NewJDialog.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void setTranslationLanguage(String friendlyName){
        translationLang = languageCodeGenerator.getCode(friendlyName);
        selectedLangLabel.setText("Translated to " + friendlyName);
        translateDirectionWords();
        
    }
    
    private void translateDirectionWords(){
                Translator tran;
        try {
            tran = new Translator();
            System.out.println(translationLang);
            northTranLabel.setText(parseTranslatorXML(tran.translate(northOrigLabel.getText(), translationLang)));
            southTranLabel.setText(parseTranslatorXML(tran.translate(southOrigLabel.getText(), translationLang)));
            eastTranLabel.setText(parseTranslatorXML(tran.translate(eastOrigLabel.getText(), translationLang)));
            westTranLabel.setText(parseTranslatorXML(tran.translate(westOrigLabel.getText(), translationLang)));
            leftTranLabel.setText(parseTranslatorXML(tran.translate(leftOrigLabel.getText(), translationLang)));
            rightTranLabel.setText(parseTranslatorXML(tran.translate(rightOrigLabel.getText(), translationLang)));
            straightTranLabel.setText(parseTranslatorXML(tran.translate(rightOrigLabel.getText(), translationLang)));



        
        } catch (IOException ex) {
            Logger.getLogger(NewJDialog.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    
    private void englishLangButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_englishLangButtonActionPerformed
        
        setTranslationLanguage(englishLangButton.getText());
    }//GEN-LAST:event_englishLangButtonActionPerformed

    private void spanishLangButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spanishLangButtonActionPerformed
        setTranslationLanguage(spanishLangButton.getText());

    }//GEN-LAST:event_spanishLangButtonActionPerformed

    private void hindiLangButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hindiLangButtonActionPerformed
        setTranslationLanguage(hindiLangButton.getText());
    }//GEN-LAST:event_hindiLangButtonActionPerformed

    private void moreLangComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moreLangComboBoxActionPerformed
        // TODO add your handling code here:
        String selectedLanguage = (String) moreLangComboBox.getSelectedItem();
        setTranslationLanguage(selectedLanguage);
    }//GEN-LAST:event_moreLangComboBoxActionPerformed

    private static String parseTranslatorXML(String input){
        int front = 0;
        while(input.charAt(front) != '>'){
            front++;
        }
        front++;
        int back = front;
        while(input.charAt(back) != '<'){
            back++;
        }
        if(front == back){
            return "";
        } else {
            return input.substring(front, back);
        }
        
        
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NewJDialog dialog = new NewJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel detectedLabel;
    private javax.swing.JLabel eastOrigLabel;
    private javax.swing.JLabel eastTranLabel;
    private javax.swing.JButton englishLangButton;
    private javax.swing.JButton hindiLangButton;
    private javax.swing.JTextArea inputTextArea;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel leftOrigLabel;
    private javax.swing.JLabel leftTranLabel;
    private javax.swing.JComboBox<String> moreLangComboBox;
    private javax.swing.JLabel northOrigLabel;
    private javax.swing.JLabel northTranLabel;
    private javax.swing.JTextArea outputTextArea;
    private javax.swing.JLabel rightOrigLabel;
    private javax.swing.JLabel rightTranLabel;
    private javax.swing.JLabel selectedLangLabel;
    private javax.swing.JLabel southOrigLabel;
    private javax.swing.JLabel southTranLabel;
    private javax.swing.JButton spanishLangButton;
    private javax.swing.JLabel straightOrigLabel;
    private javax.swing.JLabel straightTranLabel;
    private javax.swing.JLabel westOrigLabel;
    private javax.swing.JLabel westTranLabel;
    // End of variables declaration//GEN-END:variables
}
